//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class businfo
    {
        public int busid { get; set; }
        public string boardingpoint { get; set; }
        public Nullable<System.DateTime> traveldate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> rating { get; set; }
    }
}
